### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by rgalanakis** [webhookdb/webhookdb#184]
- [x] Fix contact form
- [x] Clean out old tags
- [x] Cut a new CLI release
- [x] Ensure newest WASM is on website
- [x] Upload demo video to site
- [x] Add GIF of demo video
- [x] Ship latest API
- [x] Make sure contact form works
- [x] Finish documentation review
- [x] Remove 'docker' installation instructions (since it can't store creds)

*Migrated from [webhookdb-api#184](https://github.com/lithictech/webhookdb-api/issues/184). Opened by @rgalanakis*

Opened at: 2022-02-15T20:04:16Z\
Closed at: 2022-03-17T22:25:53Z
