### ISSUE TITLE
Go-live checklist

### ISSUE THREAD

**Issue by rgalanakis** [webhookdb/webhookdb#33]
- [ ] Finish subscriptions functionality (@natalithic)
- [ ] Once CLI have release binaries published, switch paths in marketing repo to 'latest' from 0.1.0
- [x] Polish: center integrations (@ernes7)
- [ ] Proofread documentation and website
- [ ] Add 'roll credentials' command (@rgalanakis)
- [ ] Write Product Hunt post (@natalithic)
- [x] Fix broken deploy in netlify
- [ ] Fix download instructions (@ernes7)

*Migrated from [webhookdb-api#33](https://github.com/lithictech/webhookdb-api/issues/33). Opened by @rgalanakis*

Opened at: 2021-07-19T23:53:23Z\
Closed at: 2021-09-13T21:38:57Z
