### ISSUE TITLE
Presentation checklist

### ISSUE THREAD

**Issue by rgalanakis** [webhookdb/webhookdb#516]
By Oct 16:

- [x] Record our versions
- [x] Natalie cuts them together
- [x] Upload and share with Lukasz
- [x] Export presentation and add to Git
- [x] Publish Git repo
- [x] Add CI

Before Nov 1:

- [x] Add API to call externally
- [x] Host it in Heroku
- [x] Add DNS entry
- [x] Add link to service to README

*Migrated from [webhookdb-api#516](https://github.com/lithictech/webhookdb-api/issues/516). Opened by @rgalanakis*

Opened at: 2022-10-13T17:35:22Z\
Closed at: 2022-10-19T20:27:50Z
